version: "3.9"

services:
  postgres:
    build: ./postgres
    container_name: apiscan-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: apiscan
      POSTGRES_USER: apiscan
      POSTGRES_PASSWORD: apiscan
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: apiscan-redis
    ports:
      - "6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped

volumes:
  postgres_data:
